# for development

version: "3"

services:
  app:
    image: ecommerce-tech-store-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./prisma:/app/prisma
      - ./src:/app/src
      - ./public:/app/public
    env_file:
      - .env.development
  db:
    image: postgres:15.6
    env_file:
      - .env.development
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db-data:
