# for development

version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./src:/app/src
      - ./public:/app/public
  db:
    image: postgres:15.6
    restart: always
    env_file:
      - .env.development
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:
