import type { Metadata } from "next"
import "./globals.css"
import { cn } from "@/lib/utils"
import { Poppins } from "next/font/google"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import WebsiteSupport from "@/components/WebsiteSupport"

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "600"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={cn(poppins.className, "max-w-full")}>
        <Header />
        <main>{children}</main>
        <WebsiteSupport />
        <Footer />
      </body>
    </html>
  )
}
